server:
  port: 5000

spring:
  application:
    name: spring-demo
  jpa:
    hibernate:
      globally-quoted-identifiers: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: update
    datasource:
      url: ${DB_URL:jdbc:h2:mem:testdb}
      driverClassName: org.h2.Driver
      username: ${DB_USER:sa}
      password: ${DB_PSWD:}
  h2:
    console:
      enabled: false
logging:
  level:
    root: INFO
#---------------------------------jwt-------------------------------------------------#
jwt:
  token:
    secret: abcxyz123
#---------------------------------sentry-------------------------------------------------#
mockup:
  enabled:
    sentry: false
    dsn:
      url:
    application:
      environment: dev
#---------------------------------openapi-------------------------------------------------#
springdoc:
  swagger-ui:
    disable-swagger-default-url=true:
#---------------------------------rate limit-------------------------------------------------#
rate:
  limit:
    enabled: false
    request:
      time: 1
      limit: 3

#------------------------------------twilio configuration------------------------------------#

twilio:
  account:
    sid: yourTwilioAccountSID
  auth:
    token: yourTwilioAuthToken
  phone:
    number: yourTwilioNumber

#------------------------------------vonage configuration------------------------------------#

vonage:
  api:
    key: yourVonageAPIKey
    secret: yourVonageAPISecret


#------------------------------------textgrid configuration------------------------------------#

textgrid:
  authToken: yourTextgridAuthToken
  accountsid: yourTextgridAccountSID
